import { objectType } from 'nexus'

export const Champion = objectType({
  name: 'Champion',
  definition(t) {
    t.model.blurb()
    t.model.champId()
    t.model.dateCreated()
    t.model.dateModified()
    t.model.id()
    t.model.imageFull()
    t.model.imageGroup()
    t.model.imageH()
    t.model.imageSprite()
    t.model.imageW()
    t.model.imageX()
    t.model.imageY()
    t.model.infoAttack()
    t.model.infoDefense()
    t.model.infoDifficulty()
    t.model.infoMagic()
    t.model.key()
    t.model.name()
    t.model.partype()
    t.model.statsArmor()
    t.model.statsArmorPerLevel()
    t.model.statsAttackDamage()
    t.model.statsAttackDamagePerLevel()
    t.model.statsAttackRange()
    t.model.statsAttackSpeed()
    t.model.statsAttackSpeedPerLevel()
    t.model.statsCrit()
    t.model.statsCritPerLevel()
    t.model.statsHP()
    t.model.statsHPPerLevel()
    t.model.statsHPRegen()
    t.model.statsHPRegenPerLevel()
    t.model.statsMP()
    t.model.statsMPPerLevel()
    t.model.statsMPRegen()
    t.model.statsMPRegenPerLevel()
    t.model.statsMoveSpeed()
    t.model.statsSpellBlock()
    t.model.statsSpellBlockPerLevel()
    t.model.tags()
    t.model.title()
    t.model.version()
  },
})